apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push-with-ca
  namespace: privileged-pods
spec:
  params:
    - name: git-url
    - name: git-revision
      default: main
    - name: image-url
  workspaces:
    - name: source
  steps:
    - name: update-ca
      image: debian:bullseye
      script: |
        #!/bin/bash
        set -e
        apt-get update && apt-get install -y ca-certificates git
        mkdir -p /usr/local/share/ca-certificates
        cp /certs/ca-cert.crt /usr/local/share/ca-certificates/ca-cert.crt
        update-ca-certificates
      volumeMounts:
        - name: cert-volume
          mountPath: /certs
    - name: clone
      image: alpine/git
      script: |
        git clone $(params.git-url) --branch $(params.git-revision) $(workspaces.source.path)
    - name: buildah
      image: quay.io/buildah/stable
      securityContext:
        privileged: true
      script: |
        set -e
        cd $(workspaces.source.path)
        echo "Logging into Quay..."
        buildah login --tls-verify=true -u $QUAY_USER -p $QUAY_PASSWORD quay-nonprod.elevancehealth.com
        echo "Building image..."
        buildah bud --tls-verify=true -t $(params.image-url) .
        echo "Pushing image..."
        buildah push --tls-verify=true $(params.image-url)
      env:
        - name: QUAY_USER
          valueFrom:
            secretKeyRef:
              name: quay-auth-token
              key: user
        - name: QUAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: quay-auth-token
              key: password
      volumeMounts:
        - name: cert-volume
          mountPath: /etc/ssl/certs
  volumes:
    - name: cert-volume
      configMap:
        name: dummy-ca-cert

---

apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
  namespace: privileged-pods
spec:
  params:
    - name: git-url
    - name: git-revision
      default: main
    - name: image-url
  workspaces:
    - name: shared-workspace
  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push-with-ca
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: image-url
          value: $(params.image-url)
      workspaces:
        - name: source
          workspace: shared-workspace
