apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: run-build-and-push
  namespace: privileged-pods
spec:
  pipelineRef:
    name: build-and-push-pipeline
  params:
    - name: git-url
      value: https://github.com/8130092157/Implementing-DevOps.git
    - name: git-revision
      value: main
    - name: image-url
      value: quay-nonprod.elevancehealth.com/an983995ad/demo:abhay
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: shared-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
