apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-build-push
spec:
  params:
    - name: repo-url
      type: string
    - name: image-name
      type: string
    - name: image-tag
      type: string
  steps:
    - name: clone-repo
      image: alpine/git
      script: |
        #!/bin/sh
        git clone "$(params.repo-url)" /workspace/git-source

    - name: build-image
      image: quay.io/containers/podman
      script: |
        #!/bin/sh
        cd /workspace/git-source
        podman build -t "$(params.image-name):$(params.image-tag)" .

    - name: login-dockerhub
      image: quay.io/containers/podman
      script: |
        #!/bin/sh
        podman login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
      env:
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: dockerhub-secret
              key: username
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dockerhub-secret
              key: password

    - name: push-image
      image: quay.io/containers/podman
      script: |
        #!/bin/sh
        podman tag "$(params.image-name):$(params.image-tag)" "$(params.image-name):latest"
        podman push "$(params.image-name):$(params.image-tag)"
        podman push "$(params.image-name):latest"

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-clone-build-push
spec:
  params:
    - name: repo-url
      type: string
    - name: image-name
      type: string
    - name: image-tag
      type: string
  tasks:
    - name: clone-build-push-task
      taskRef:
        name: clone-build-push
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: image-name
          value: $(params.image-name)
        - name: image-tag
          value: $(params.image-tag)